version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      # context: ../frontend      # Lieu du dossier 'frontend' dans le projet
      dockerfile: ./Dockerfile  # Lieu du dockerfile, par rapport au context
    image: portfolio:frontend
    restart: always
    ports:
      - "8081:80"
