version: '3.8'
services:
  frontend:
    container_name: charles
    build:
      dockerfile: ./Dockerfile  # Lieu du dockerfile, par rapport au context
      args:       # Permet au front d'avoir les adresses ip du front et du back
        VITE_FRONT_URL: https://51.254.119.241

    image: studi0426/charles:frontend
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    networks: 
      - charles-networks

networks:
  charles-networks:
    driver: bridge
    ipam: 
      driver: default