version: '3.8'
services:
charles:
  container_name: charles
  build:
    context: ./Portfolio # Lieu du dossier 'frontend' dans le projet
    dockerfile: ./Dockerfile # Lieu du dockerfile, par rapport au context
    args:
      # Permet au front d'avoir les adresses ip du front et du back
      VITE_FRONT_URI: charles/
      VITE_FRONT_URL: http://51.254.119.241

  image: studi0426/charles:frontend
  restart: always
  ports:
    - "127.0.0.1:8081:80"
  networks:
    - charles-network

networks:
  charles-network:
    driver: bridge
    ipam:
      driver: default
