name: Deploy portfolio project on server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH 
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy modified files via rsync
      run: |
        rsync -avz --exclude='.git*' -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" --delete ${{ github.workspace }}/ ${{ secrets.USER }}@${{ secrets.SERVER_IP }}:/srv/Portfolio

    - name: Deploy
      run: |
        ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /srv
        docker compose stop charles
        docker container prune --force
        docker image prune --force
        docker compose build charles
        docker compose up -d charles
        EOF
